#!/bin/bash

curl -O https://data.dra2020.net/file/dra-datafiles/_AL_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_AK_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_AZ_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_AR_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_CA_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_CO_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_CT_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_DE_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_FL_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_GA_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_HI_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_ID_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_IL_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_IN_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_IA_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_KS_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_KY_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_LA_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_ME_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_MD_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_MA_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_MI_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_MN_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_MS_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_MO_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_MT_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_NE_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_NV_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_NH_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_NJ_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_NM_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_NY_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_NC_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_ND_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_OH_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_OK_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_OR_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_PA_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_RI_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_SC_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_SD_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_TN_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_TX_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_UT_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_VT_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_VA_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_WA_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_WV_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_WI_2020_VD_tabblock.vtd.datasets.geojson
curl -O https://data.dra2020.net/file/dra-datafiles/_WY_2020_VD_tabblock.vtd.datasets.geojson
